language: php

php:
  - 8.1

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  global:
    - SYMFONY_PHPUNIT_DIR=$HOME/symfony-bridge/.phpunit

before_install:
  - phpenv config-rm xdebug.ini || true
  - composer self-update

install:
  - composer install
  - ./vendor/bin/simple-phpunit install

script:
  - ./vendor/bin/simple-phpunit
