version: '3.9'

services:
  db:
    image: postgres:15.2
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_management
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data

  php:
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    depends_on:
      - db
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  db-data:
